version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_IMPORT: /opt/keycloak/data/import/realm.json
    volumes:
      - ./realm.json:/opt/keycloak/data/import/realm.json
    command: start-dev --import-realm
    ports:
      - "8080:8080"
